import { TestStep, QAPulseGenConfig, GeneratedTest, GeneratedFile } from '../core/types';

function indent(n: number): string {
  return '  '.repeat(n);
}

function renderCypressStep(step: TestStep, depth = 2): string {
  const i = indent(depth);
  const comment = step.comment ? `${i}// ${step.comment}\n` : '';

  switch (step.type) {
    case 'navigate':
      return `${comment}${i}cy.visit('${step.url}');`;

    case 'click':
      return `${comment}${i}cy.get('${step.selector}').click();`;

    case 'fill':
      return `${comment}${i}cy.get('${step.selector}').clear().type('${step.value || ''}');`;

    case 'select':
      return `${comment}${i}cy.get('${step.selector}').select('${step.value || ''}');`;

    case 'check':
      return `${comment}${i}cy.get('${step.selector}').${step.value === 'uncheck' ? 'uncheck' : 'check'}();`;

    case 'press':
      return `${comment}${i}cy.get('${step.selector || 'body'}').type('{${step.key?.toLowerCase() || 'enter'}}');`;

    case 'hover':
      return `${comment}${i}cy.get('${step.selector}').trigger('mouseover');`;

    case 'screenshot':
      return `${comment}${i}cy.screenshot('checkpoint-${Date.now()}');`;

    case 'wait':
      return `${comment}${i}cy.wait(1000);`;

    case 'assert': {
      const a = step.assertion;
      if (!a) return '';
      switch (a.type) {
        case 'url':
          return `${comment}${i}cy.url().should('include', '${a.expected}');`;
        case 'title':
          return `${comment}${i}cy.title().should('eq', '${a.expected}');`;
        case 'visible':
          return `${comment}${i}cy.get('${a.selector}').should('be.visible');`;
        case 'text':
          return `${comment}${i}cy.get('${a.selector}').should('contain.text', '${a.expected}');`;
        case 'value':
          return `${comment}${i}cy.get('${a.selector}').should('have.value', '${a.expected}');`;
        case 'count':
          return `${comment}${i}cy.get('${a.selector}').should('have.length', ${a.expected});`;
        default:
          return '';
      }
    }

    case 'api': {
      const req = step.apiRequest;
      if (!req) return '';
      const bodyLine = req.body ? `\n${i}  body: ${req.body},` : '';
      return `${comment}${i}cy.request({\n${i}  method: '${req.method}',\n${i}  url: '${req.url}',${bodyLine}\n${i}}).then((response) => {\n${i}  expect(response.status).to.eq(${req.expectedStatus || 200});\n${i}});`;
    }

    default:
      return '';
  }
}

function generateCypressTS(testName: string, steps: TestStep[], baseUrl?: string): string {
  const stepLines = steps.map(s => renderCypressStep(s)).filter(Boolean).join('\n');
  const baseUrlComment = baseUrl ? `// Base URL: ${baseUrl} — set in cypress.config.ts\n\n` : '';

  return `// Generated by QAPulseSK-gen — QAPulse by SK
// https://skakarh.com · https://github.com/QAPulse-by-SK
${baseUrlComment}
describe('${testName}', () => {
  it('should complete the user flow', () => {
${stepLines}
  });
});
`;
}

function generateCypressJS(testName: string, steps: TestStep[], baseUrl?: string): string {
  return generateCypressTS(testName, steps, baseUrl); // Cypress JS/TS syntax is identical
}

function generateCypressPOM(testName: string, steps: TestStep[]): { pageObject: string; test: string } {
  const className = testName.replace(/[^a-zA-Z0-9]/g, '') + 'Page';
  const navigateSteps = steps.filter(s => s.type === 'navigate');
  const firstUrl = navigateSteps[0]?.url || '/';

  const methods = steps
    .filter(s => s.selector && (s.type === 'click' || s.type === 'fill'))
    .map(s => {
      const name = s.selector!.replace(/[^a-zA-Z0-9]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '').toLowerCase().slice(0, 25);
      if (s.type === 'click') return `  ${name}() {\n    cy.get('${s.selector}').click();\n    return this;\n  }`;
      if (s.type === 'fill') return `  ${name}(value) {\n    cy.get('${s.selector}').clear().type(value);\n    return this;\n  }`;
      return '';
    })
    .filter((v, i, a) => v && a.indexOf(v) === i)
    .join('\n\n');

  const pageObject = `// Generated by QAPulseSK-gen — QAPulse by SK

class ${className} {
  visit() {
    cy.visit('${firstUrl}');
    return this;
  }

${methods}
}

export default new ${className}();
`;

  const test = `// Generated by QAPulseSK-gen — QAPulse by SK
import ${className.toLowerCase()} from '../pages/${className}';

describe('${testName}', () => {
  it('should complete the user flow', () => {
    ${className.toLowerCase()}.visit();
${steps.map(s => renderCypressStep(s)).filter(Boolean).join('\n')}
  });
});
`;

  return { pageObject: pageObject, test };
}

export function generateCypressTests(
  steps: TestStep[],
  testName: string,
  config: QAPulseGenConfig
): { tests: GeneratedTest[]; pomFiles?: GeneratedFile[] } {
  const tests: GeneratedTest[] = [];
  const pomFiles: GeneratedFile[] = [];

  const ext = config.language === 'typescript' ? 'ts' : 'js';

  if (config.usePOM) {
    const className = testName.replace(/[^a-zA-Z0-9]/g, '') + 'Page';
    const { pageObject, test: testFile } = generateCypressPOM(testName, steps);

    pomFiles.push({ filename: `cypress/pages/${className}.${ext}`, content: pageObject });
    tests.push({
      filename: `cypress/e2e/${testName.replace(/\s+/g, '-').toLowerCase()}.cy.${ext}`,
      content: testFile,
      framework: 'cypress',
      language: config.language,
      inputType: 'har',
      stepCount: steps.length,
    });
  } else {
    const content = config.language === 'typescript'
      ? generateCypressTS(testName, steps, config.baseUrl)
      : generateCypressJS(testName, steps, config.baseUrl);

    tests.push({
      filename: `cypress/e2e/${testName.replace(/\s+/g, '-').toLowerCase()}.cy.${ext}`,
      content,
      framework: 'cypress',
      language: config.language,
      inputType: 'har',
      stepCount: steps.length,
    });
  }

  return { tests, pomFiles: pomFiles.length > 0 ? pomFiles : undefined };
}
